dog_api_url = "https://dog.ceo/api/breeds/image"
by_breed = "https://dog.ceo/api/breed/"
openbrewerydb_url = "https://api.openbrewerydb.org/v1/breweries"
jsonplaceholder_url = "https://jsonplaceholder.typicode.com/todos"
ya_url = "https://ya.ru"
